### ISSUE TITLE
安装后，无法运行

### ISSUE THREAD

**Issue by caesarljs** [raphaelvallat/entropy#1]
安装后，提示缺少函数

**Comment by vpolimenov** [comment]
I had the same issue, but deactivating the conda environment and activating it again (and obvously restarting the kernel) the issue went away.

Few things to check:

1. There is a package `entropy` that could be installed - so uninstall if it's there.
2. Follow the instructions carefully
3. Make sure you install in the correct environment
4. Deactivate and Activate again your env.
5. Make sure Jupyter is running in that same environment as well.
