### ISSUE TITLE
Publish in PyPi with different name

### ISSUE THREAD

**Issue by Ricocotam** [raphaelvallat/entropy#11]
Hi,
Thanks for the package, it's awesome !
Why don't you want to publish it on PyPi under a different name ? You'd get way more users, starting by me. Handling packages manually is not practical by any means. Your code is way harder to use in production than it would be on PyPi.

That's just a suggestion, great work on the package !

**Comment by raphaelvallat** [comment]
Hi @Ricocotam!

Thanks for the suggestion. I haven't really thought about that, but now that you mention it I think I could change the name to "antropy" (keeping in line with the long tradition of animal names in Python). I'll have to think more about it in the next days, but I'm definitely not against it.

If anyone else thinks it'd be a good idea, or have a cool idea for a new name (available on PyPi), please do let me know!

Thanks,
Raphael

**Comment by raphaelvallat** [comment]
Good news! I have now duplicated entropy to another GitHub repository named AntroPy (https://github.com/raphaelvallat/antropy). AntroPy can be installed with `pip install antropy`. 

I will progressively deprecate EntroPy in the next weeks / months.
