### ISSUE TITLE
Joint Entropy?

### ISSUE THREAD

**Issue by xanderdunn** [raphaelvallat/entropy#12]
Many thanks for providing these great entropy estimators as open source software. 

Is there a way to calculate joint entropy using these entropy approximations? The ability to calculate join entropies would allow the calculation of additional information measures such as mutual information and conditional mutual information. 

The [entropy_estimators](https://github.com/paulbrodersen/entropy_estimators/blob/master/entropy_estimators/continuous.py#L276) package, which is estimating entropy using a k-nearest-neighbor approach, calculates the joint entropy of X, Y by concatenating their values with `np.c_[x, y]`. This doesn't apply here because the inputs are all coerced into a 0-dimensional vector, and this approach likely doesn't make sense outside of the k-nearest neighbor approach. Is there an alternate way to think about joint entropies with respect to these estimators? In particular, I'm working with the approximate, sample, and permutation entropies.

**Comment by raphaelvallat** [comment]
Hi @xanderdunn,

I honestly don't know what would be the best approach to calculate joint permutation/sample/approximate entropies. The current package was mostly designed to improve the speed of pre-existing functions on 1D timeseries, and I don't have enough theoretical background to create such new functions on _N_D data from scratch. It seems that two recent papers looked at joint permutation entropy, ([here](https://doi.org/10.1016/j.jhydrol.2017.07.003) and [here](https://www.sciencedirect.com/science/article/abs/pii/S0378437118313098)). If anyone wants to give it a try, please feel free to submit a PR. You may also want to look at the [Nitime](http://nipy.org/nitime/api/generated/nitime.algorithms.entropy.html) package which has a bunch of functions to calculate (joint) entropy and mutual information.

Thanks,
Raphael

**Comment by xanderdunn** [comment]
Thanks very much Raphael! These links are helpful. I'll have a look and see what I can come up with. 

I'll go ahead and close this issue since it's outside the original scope of the project. I'll open a Pull Request if I get anything interesting working. 👍
