### ISSUE TITLE
Inaccuracies in LZ complexity estimates

### ISSUE THREAD

**Issue by pranaysy** [raphaelvallat/entropy#14]
Hi Raphael!

I'm a big fan of your work and I am a regular user of your packages `entropy`, `pingouin` as well as `yasa`. These are great contributions, and I thank you for them :)

I've been relying on your Numba implementation of [`lempel_ziv_complexity`](https://github.com/raphaelvallat/entropy/blob/3bf3b6e937687e77965ecb5bfdc69e2a0f059363/entropy/entropy.py#L485) for various analyses I'm working on. I found myself in need for a faster implementation and comments in your code pointed me to [Naereen's Cython implementation](https://github.com/Naereen/Lempel-Ziv_Complexity/blob/master/src/lempel_ziv_complexity.pyx).

I briefly compared the timings and accuracy of your Numba version with both the pure Python and Cython versions by Naereen. With string inputs, somehow the Numba version is slower than pure Python, both of which are slower than the Cython version. But more importantly, the estimates are different. The pure Python and Cython versions return the exact same estimates, but the Numba version returns different estimates, which are usually smaller.

I tried all three methods on `1000` randomly generated strings each for lengths `[10, 100, 1000, 10000]`  Here's a quick visual summary of the timings, raw estimates and differences between the 3. The difference in estimates grows with string length. :(

![test](https://user-images.githubusercontent.com/8765418/105970531-7ac1da00-60af-11eb-90ee-2aa9d2ddfeb1.png)

I tried out a few examples by hand too. For example: 
 - the string `rpfqvnradv` is decomposed by LZ76 to `['r', 'p', 'f', 'q', 'v', 'n', 'ra', 'd']` or `8` unique substrings
   - Both the Cython and pure Python versions return `8`
   - The Numba version returns `9`
 - the string `msduldaefd` is decomposed by LZ76 to `['m', 's', 'd', 'u', 'l', 'da', 'e', 'f']` or `8` unique substrings
   - Both the Cython and pure Python versions return `8`
   - The Numba version returns `9`
 
I haven't spent any time troubleshooting the Numba code beyond this. If I get time to go through your implementation, I'll see if there's anything I can do to help or address this issue.

---
Here are versions of packages I've used on Python 3.8.5:
 - Numba - 0.51.2
 - Numpy - 1.19.2
 - EntroPy - 0.1.2
 - Cython - 0.29.21

System: 10th Gen Intel Core i5-1035G4 running PopOS 20.10, kernel 5.8; gcc 10.2.0; llvmlite 0.34.0

**Comment by raphaelvallat** [comment]
Hi @pranaysy,

Thank you so much for doing this extensive dive into the LZ function! I've always wanted to do it, but was too lazy for it, so glad you did it :-) Two things:

1) I've also noticed that the Numba version was actually quite slow. Given the results from your test, I think we should switch to a Pure Python implementation only.

2) So I've actually tested the LZ function against a Matlab script, as shown below. However, I've only tested with small sequences, so I probably have missed an error that becomes more apparent when the sequence becomes longer. I also need to make sure that the Matlab script and the Pure Python / Cython implementation are consistent.

https://github.com/raphaelvallat/entropy/blob/3bf3b6e937687e77965ecb5bfdc69e2a0f059363/entropy/tests/test_entropy.py#L72-L103

Thanks again!
Raphael

**Comment by pranaysy** [comment]
Hey Raphael!

Thank you for your response :)

I could take a quick glance and you were right in pointing out in (2) that the MATLAB script and the Python/Cython versions need to be consistent. I decided to check that out.

I went through Quang Thai's MATLAB implementation you'd linked to - thanks a lot for that. He talks about two distinct LZ decompositions - exhaustive and primitive, which then led me to the original 1976 IEEE paper.

---
Using the example from the paper (Section III and Lemma 6 of Section IV)
```
    S = [0,0,0,1,1,0,1,0,0,1,0,0,0,1,0,1]
```
    
**The MATLAB version, _exhaustive_ variant**, returns LZ complexity of 6, the substrings look like this:
```
    0, 001, 10, 100, 1000, 101
```
This agrees with the paper:
 > ![image](https://user-images.githubusercontent.com/8765418/106452407-d7f1cd00-64ad-11eb-9498-ba833cff0fba.png)
    

**The MATLAB version, _primitive_ variant**, returns LZ complexity of 9, the substrings look like this:
```
    0, 001, 10, 10, 0, 10, 00, 10, 1   # 5 unique
```
This too agrees with the paper:
 > ![image](https://user-images.githubusercontent.com/8765418/106452468-ee982400-64ad-11eb-8de1-9d970bb334c6.png)
    
**Your Numba version** returns LZ complexity of 6, in agreement with the exhaustive variant. I haven't yet modified the code to return substrings

**Naereen's version**, interestingly -  returns LZ complexity of 7 with different substrings:
```
    0, 00, 1, 10, 100, 1000, 101
```
This is **clearly inconsistent** with either variant from the reference paper - I'd argue that it is sufficient evidence against its correctness (?)

---

Further, I could try estimation with some 20-25 long-ish sequences manually across implementations, and _your Numba version appears to be in agreement with the exhaustive LZ complexity from the MATLAB variant._ Naereen's version almost always returned higher estimates, although they were smaller than the primitive variant - likely due to non-unique elements in the latter. 

Estimates appear to follow this relation:
 ```
    Numba == MATLAB (exhaustive) < Python/Cython (Naereen) < MATLAB (primitive)
```
  
---

This is preliminary, not really rigorous. I am yet to do a more comprehensive analysis, but _we should stick with your current implementation for correctness_. I think some speed-ups are possible, and can definitely address (1). I'll try to work on both - analysis for correctness as well as performance. 

Let me know what you think :)

Best,
Pranay

**Comment by raphaelvallat** [comment]
Hi @pranaysy,

This is really fantastic, well done! What is really surprising is that @Naereen has also created [a notebook that describes  several implementations of LZ](https://perso.crans.org/besson/publis/Lempel-Ziv_Complexity.git/Short_study_of_the_Lempel-Ziv_complexity.html#Python-implementation) (Python, Cython and Numba), and it seems like they are all consistent with Matlab / Entropy (i.e. they return 6).

![image](https://user-images.githubusercontent.com/25703792/106531382-f69e9680-64a2-11eb-9ebc-661cbceb12b8.png)

@Naereen sorry to involve you in this discussion, but is there a reason why the notebooks and Python package are inconsistent? Having your feedback would be very valuable to understand what is the ground-truth for this function.

Thanks to both of you,
Raphael

**Comment by pranaysy** [comment]
Hey @raphaelvallat 

Thanks!
Yes you're right, it seems that @Naereen's implementation underwent a change in commit [`5537546`](https://github.com/Naereen/Lempel-Ziv_Complexity/commit/5537546dfcba37dae1079aeb8f8b57d68171ee7e) in order to fix a similar [issue that was raised](https://github.com/Naereen/Lempel-Ziv_Complexity/issues/5). These changes were made to both the Python and Cython versions - so the algorithm in the notebooks is no longer the algorithm in the current package, hence the deviation.

Naereen's insights would indeed be highly valuable :)

Best,
Pranay

**Comment by Naereen** [comment]
Hi @pranaysy and @raphaelvallat,
No problem, thanks for including me and for having tried [my tiny project](https://GitHub.com/Naereen/Lempel-Ziv_Complexity.git/).

@pranaysy is right, someone pointed an error about a year ago (I had forgotten about it), and I fixed it by changing the Python and Cython versions. I hope they both got fixed!
I didn't think about updating the notebook, sorry.

I'll try to do it asap!

**Comment by raphaelvallat** [comment]
Hi @Naereen,

Thank you so much! So sorry to be a bother, but could you give more details on what was wrong with the previous implementation? And why the new implementation gives results that are different from the original paper?

Merci beaucoup :-) 
Raphael

**Comment by pranaysy** [comment]
Hi @Naereen and @raphaelvallat,

Thanks for addressing these concerns :)

I ran some benchmarks for LZ complexity estimation based on 5 different implementations:
 1. Naereen's current Cython implementation
 2. Naereen's current Python implementation
 3. Naereen's previous Python implementation (prior to patching issue 5 with commit [`5537546`](https://github.com/Naereen/Lempel-Ziv_Complexity/commit/5537546dfcba37dae1079aeb8f8b57d68171ee7e) that altered estimates)
 4. Raphael's Numba implementation (based on 3 above)
 5. Quang Thai's MATLAB implementation

I sampled randomly generated binary sequences - 1000 each for lengths 100, 1000 and 10000 in MATLAB and ran the above 5 methods. I found that **implementations 3, 4 and 5 gave identical estimates** for all 3000 sequences. 1 and 2 give the same estimates but these were always different from 3/4/5. I've attached the LZC estimates as well as the raw sequences just in case.
 - [lzc_benchmark_sequences.zip](https://github.com/raphaelvallat/entropy/files/5920146/lzc_benchmark_sequences.zip)
 - [lzc_estimates.csv.zip](https://github.com/raphaelvallat/entropy/files/5920153/lzc_estimates.csv.zip)

I think @Naereen's new implementation lead to some [potentially breaking changes](https://github.com/Naereen/Lempel-Ziv_Complexity/issues/5#issuecomment-772676123)? The previous version - which appears to have been used by Raphael, and is also in the notebooks - appears to be correct. 

Hope this helps. Once we agree on correctness, I want to see if something can be done about performance :)

Best,
Pranay

**Comment by raphaelvallat** [comment]
Up @pranaysy @Naereen! Do we know what is the ground truth? Otherwise, I think I will just re-write the function in pure Python for performance. Thanks

**Comment by pranaysy** [comment]
Hi @raphaelvallat 

Since yours and Naereen's earlier implementations agreed with Quong Thai's MATLAB implementation, I have chosen to move along with your Numba version.

Numba isn't particularly fast for strings ([for instance](https://stackoverflow.com/a/61703701)) so I adapted it for 64-bit unsigned integer arrays.

Please have a look at [**this gist** for benchmarks](https://gist.github.com/pranaysy/268fcc716c45781ca770fc569cbb2bf9) (_it is much faster!_). [Here's a summary plot](https://gist.github.com/pranaysy/268fcc716c45781ca770fc569cbb2bf9#gistcomment-3643465). Adapting it should be straightforward I think and is definitely preferable to pure Python :)

I have implemented the same in Cython, which gives me roughly a 30% speedup over the Numba one, which is nice for longer arrays. Let me know if that interests you.

Best,
Pranay

**Comment by raphaelvallat** [comment]
Thanks @pranaysy, as always great work! So just to be clear: does your new Numba implementation work with strings such as "Hello World!", or only on integer arrays? Also, just curious how fast is the Cython version compared to the others?

**Comment by Naereen** [comment]
Hi guys, sorry I've been extra busy the last few weeks.
I'll try to read everything again and let you know what I think.

Regarding my implementations, honestly this was a tiny side project, not something I did seriously.
And mathematically I think I never really understood the definition and algorithm for the Lempel-Ziv complexity... I adapted into Python a code I saw somewhere, tested a couple of different optimization in a notebook, to compare between Numba and Cython, and when I saw that Pypi has no module offering this function, I uploaded it, but more as an exercise for me to learn how to do that (I did it [more seriously a year later](https://smpybandits.github.io/)), than to be really useful to people...

When someone opened an issue saying my code was wrong (the commit mentioned above by @pranaysy), their justification seemed correct (but again I'm not sure to understand the definition), so I changed the code.
I guess I was lazy and didn't updated the notebook, only the Python and others (not even sure) code. Sorry, doing a PhD means sometimes you get lazy on side project ;-)

**Comment by raphaelvallat** [comment]
No worries at all @Naereen, I completely understand :-) This is not a high-priority issue anyway. It seems that I'll probably just keep the current implementation without any changes.

Cheers,
Raphael

**Comment by Naereen** [comment]
Thanks & merci for understanding!
I'll try to come back at this during the weekend! Cheers :+1:!

**Comment by pranaysy** [comment]
Hey @raphaelvallat

The Numba implementation is _just one line away_ from working with strings!
Any input string can be converted to its numeric ASCII representation very quickly, and this integer array can now directly be passed into the Numba function.

For example:
```python
string = 'aardvark'

# Fast numpy function for converting an iterable to an array
np.fromiter(map(ord, string), count=len(string), dtype='uint64')

>>> array([ 97,  97, 114, 100, 118,  97, 114, 107], dtype=uint64) # Works with Numba
```
Since ASCII is a one-to-one mapping, the representation is lossless :)

Alternatively, you could also look at [memory views on character arrays](https://gist.github.com/tkf/2276773) from strings. (Especially if you're working with unicode characters)

---
**Numba vs Cython**
 - For arrays of size ~10,000, the difference is barely noticeable
 - For larger arrays, the Cython version can be upto ~1.4-1.5x faster
I've implemented Cython functions for both strings and arrays, the latter is generally faster:
![gist_timings_cython](https://user-images.githubusercontent.com/8765418/109161845-892e0f00-779d-11eb-8a38-9ba511fd1469.png)

---

No problem @Naereen, it's alright
Your code has been a major contribution and has inspired several other implementations! Thank you :)

**Comment by raphaelvallat** [comment]
Fantastic @pranaysy! Would you like to submit a PR with the new implementation?

**Comment by Naereen** [comment]
@pranaysy if you happen to be extremely bored :rofl:, and want to submit a PR to my package as well, I'll merge it and update on Pypi :ok_hand: !

**Comment by pranaysy** [comment]
Yes I would be happy to submit PRs to both packages :)
I'll probably get around to it by this weekend, hope that's okay

@raphaelvallat you'd prefer the Numba one - correct? (with string-to-int array conversion)
I ask this because Cython on Windows can be non-trivial to setup (except WSL) and you are currently not using it in your package.

@Naereen would you prefer the array or string cython versions? (or _both_?)

**Comment by raphaelvallat** [comment]
That sounds great @pranaysy! Yes, let's stick with Numba please. Thanks again!

**Comment by Naereen** [comment]
Thanks @pranaysy, for my GitHub project, do as you want, submit whatever modification you feel is the best solution, I'll gladly merge your PR.
