### ISSUE TITLE
Doubt regarding permutation entropy

### ISSUE THREAD

**Issue by ManiSravaniKothapalli** [raphaelvallat/entropy#2]
Hi

Here in the given code what does order=3 mean in the implementation? Please help.

Thanks
Mani Sravani

**Comment by vpolimenov** [comment]
In general:

> Order is defined as the number of possible states in which a particular system can be in

[Here](https://www.quora.com/How-do-we-define-order-in-entropy) is a good Quora discussion.

However, it's a very good question of why it was decided that 3 is the best default value.

**Comment by ManiSravaniKothapalli** [comment]
Thanks for the reply.
What does metric='chebyshev' mean? or Is there any other format for calculating Approximate Entropy?
Please do explain
Thanks in Advance

**Comment by ManiSravaniKothapalli** [comment]
app_entropy(x, order=2, metric='chebyshev') 
this is not working for me in python. It is showing the error mentioned in the screenshot
![error](https://user-images.githubusercontent.com/49665193/56855219-34cb6580-6961-11e9-9cc0-4063543e7d80.PNG)

Please help me out.

**Comment by vpolimenov** [comment]
`No module named 'entropy'` means you haven't installed the package. Check this out https://github.com/raphaelvallat/entropy/issues/1#issuecomment-478627100. 

About your previous comment: [Chebyshev distance](https://en.wikipedia.org/wiki/Chebyshev_distance)

I usually go with the `minkowski` distance as it is a generalization that unifies Euclidean distance, Manhattan distance, and Chebyshev distance.
