### ISSUE TITLE
Can't not run the code

### ISSUE THREAD

**Issue by LinzzMichael** [raphaelvallat/entropy#3]
I got error when import entropy, No module named 'llvmlite.llvmpy.ee', can you tell me how to solver it?

**Comment by raphaelvallat** [comment]
Hi @LinzzMichael ! Sorry for the late reply, for some reasons I didn't get a notification. Anyway, you need to install the llvmlite package first. Please follow the instructions here: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html

Thanks
