### ISSUE TITLE
NameError: name 'unicode_type' is not defined

### ISSUE THREAD

**Issue by talhaanwarch** [raphaelvallat/entropy#4]
Greetings Previously every things was working fine, two weeks ago.
But now i am getting this error.
`NameError: name 'unicode_type' is not defined`

I am using google colab
You can reproduce the problem by

```
!pip install git+https://github.com/raphaelvallat/entropy.git
from entropy import *
```
Thanks

**Comment by raphaelvallat** [comment]
Hi @talhaanwarch!

This is surely related either to your Python or Numba version. Please try updating Numba using `pip install --upgrade numba`. If that still does not work, can you please let me know what versions of Python, Numba, Scipy, Numpy you are using as well as your OS?

Thanks

**Comment by raphaelvallat** [comment]
As a temporary fix,

**Comment by talhaanwarch** [comment]
thank you, upgrading numba version worked.
